/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.framepack;

import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DOUGLS
 */
public class FrmConsulta extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form FrmConsulta
     */
    
    
    private void consulta(){
        String sql = "select * from mercadoria where nome = ?";
            try {
            ps = conexao.prepareStatement(sql);
            ps.setString(1, tfNome.getText());
          
            rs = ps.executeQuery();
            
            if (rs.next()){
                lblResultado.setText(rs.getString(2));
                lblRet.setText(rs.getString(3));
                
              
            } else {
                JOptionPane.showMessageDialog(null, "Dados Inválidos!");
            }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Dados inválidos!");
        }
    }
    public FrmConsulta() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblCat = new javax.swing.JLabel();
        moveis = new javax.swing.JRadioButton();
        construcao = new javax.swing.JRadioButton();
        manutencao = new javax.swing.JRadioButton();
        decoracao = new javax.swing.JRadioButton();
        concessionaria = new javax.swing.JRadioButton();
        pet = new javax.swing.JRadioButton();
        lblNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        lblRet = new javax.swing.JLabel();
        btFiltrar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(null);

        lblCat.setText("Escolha a categoria que você procura:");
        getContentPane().add(lblCat);
        lblCat.setBounds(50, 20, 300, 30);

        buttonGroup1.add(moveis);
        moveis.setText("Móveis/Eletrodomésticos");
        moveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveisActionPerformed(evt);
            }
        });
        getContentPane().add(moveis);
        moveis.setBounds(20, 70, 143, 23);

        buttonGroup1.add(construcao);
        construcao.setText("Materiais de Construção");
        getContentPane().add(construcao);
        construcao.setBounds(20, 100, 141, 23);

        buttonGroup1.add(manutencao);
        manutencao.setText("Manutenção de Computadores");
        getContentPane().add(manutencao);
        manutencao.setBounds(20, 130, 173, 23);

        buttonGroup1.add(decoracao);
        decoracao.setText("Decoração");
        getContentPane().add(decoracao);
        decoracao.setBounds(190, 70, 93, 23);

        buttonGroup1.add(concessionaria);
        concessionaria.setText("Concessionárias");
        getContentPane().add(concessionaria);
        concessionaria.setBounds(190, 100, 103, 23);

        buttonGroup1.add(pet);
        pet.setText("Pet Shops");
        pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petActionPerformed(evt);
            }
        });
        getContentPane().add(pet);
        pet.setBounds(190, 130, 73, 23);

        lblNome.setText("Informe o Nome do Produto: ");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 170, 160, 20);
        getContentPane().add(tfNome);
        tfNome.setBounds(160, 170, 180, 20);

        lblResultado.setText("Resultado: ");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(30, 220, 300, 14);

        lblRet.setText("...");
        getContentPane().add(lblRet);
        lblRet.setBounds(40, 240, 12, 14);

        btFiltrar.setText("Filtrar");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btFiltrar);
        btFiltrar.setBounds(20, 190, 61, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveisActionPerformed

    private void petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petActionPerformed

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
       if (moveis.isSelected()){
           consulta();
       } else if (construcao.isSelected()){
           consulta();
       } else if (manutencao.isSelected()){
           consulta();
       } else if (decoracao.isSelected()){
           consulta();
       } else if (concessionaria.isSelected()){
           consulta();
       } else if (pet.isSelected()){
           consulta();
       }
       
    }//GEN-LAST:event_btFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFiltrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton concessionaria;
    private javax.swing.JRadioButton construcao;
    private javax.swing.JRadioButton decoracao;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblRet;
    private javax.swing.JRadioButton manutencao;
    private javax.swing.JRadioButton moveis;
    private javax.swing.JRadioButton pet;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
