/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.framepack;

import br.com.daopack.Connecting;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DOUGLS
 */
public class TelaCadastro extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement ps = null;

    public void cadastrar() {

        String sql = "insert into tbcliente(cpf, nome, telefone, endereco, num, complemento, cep, email, senha) values(?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            ps = conexao.prepareStatement(sql);
            ps.setString(1, tfCpf.getText());
            ps.setString(2, tfNome.getText());
            ps.setInt(3, Integer.parseInt(tfTelefone.getText()));
            ps.setString(4, tfEndereco.getText());
            ps.setString(5, tfNum.getText());
            ps.setString(6, tfComplemento.getText());
            ps.setInt(7, Integer.parseInt(tfCep.getText()));
            ps.setString(8, tfEmail.getText());
            ps.setString(9, pfSenha.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso! Volte para o Menu Login");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Dados inválidos");

        }

    }

    public TelaCadastro() {
        initComponents();
        conexao = Connecting.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDesc = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        tfCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();
        tfNum = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        tfCep = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        btLimpar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        Aviso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblDesc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(255, 255, 255));
        lblDesc.setText("Preencha a Ficha de Cadastro");
        getContentPane().add(lblDesc);
        lblDesc.setBounds(210, 20, 390, 90);

        btCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar);
        btCadastrar.setBounds(200, 480, 100, 40);

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(80, 190, 70, 14);
        getContentPane().add(tfCpf);
        tfCpf.setBounds(190, 140, 240, 30);

        lblCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(255, 255, 255));
        lblCpf.setText("CPF:");
        lblCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCpfMouseEntered(evt);
            }
        });
        getContentPane().add(lblCpf);
        lblCpf.setBounds(80, 150, 70, 14);
        getContentPane().add(tfNome);
        tfNome.setBounds(190, 180, 240, 30);

        lblTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setText("Telefone:");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(80, 230, 70, 14);
        getContentPane().add(tfTelefone);
        tfTelefone.setBounds(190, 220, 240, 30);

        lblEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço:");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(80, 270, 70, 15);
        getContentPane().add(tfEndereco);
        tfEndereco.setBounds(190, 260, 170, 30);

        lblNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNum.setForeground(new java.awt.Color(255, 255, 255));
        lblNum.setText("Nº ");
        getContentPane().add(lblNum);
        lblNum.setBounds(370, 270, 70, 14);
        getContentPane().add(tfNum);
        tfNum.setBounds(390, 260, 40, 30);

        lblComplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(255, 255, 255));
        lblComplemento.setText("Complemento:");
        getContentPane().add(lblComplemento);
        lblComplemento.setBounds(80, 310, 90, 15);
        getContentPane().add(tfComplemento);
        tfComplemento.setBounds(190, 300, 170, 30);

        lblCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCep.setForeground(new java.awt.Color(255, 255, 255));
        lblCep.setText("CEP:");
        lblCep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCepMouseEntered(evt);
            }
        });
        getContentPane().add(lblCep);
        lblCep.setBounds(80, 350, 70, 14);
        getContentPane().add(tfCep);
        tfCep.setBounds(190, 340, 170, 30);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(80, 390, 70, 14);
        getContentPane().add(tfEmail);
        tfEmail.setBounds(190, 380, 250, 30);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(80, 430, 70, 14);
        getContentPane().add(pfSenha);
        pfSenha.setBounds(190, 420, 250, 30);

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(300, 480, 100, 40);

        btVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(400, 480, 100, 40);

        Aviso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Aviso.setForeground(new java.awt.Color(255, 255, 255));
        Aviso.setText("Aviso");
        getContentPane().add(Aviso);
        Aviso.setBounds(80, 110, 560, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/viewpack/FundoNovo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 980, 640);

        setSize(new java.awt.Dimension(847, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void lblCpfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCpfMouseEntered
        //Exibe aviso no lugar correspondente a Label CPF
        //Passar o cursor do mouse em cima da label
        Aviso.setText("Favor preencher com os caracteres" +"."+ "e" +"-"+"");

    }//GEN-LAST:event_lblCpfMouseEntered

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        //Retorna para o menu anterior
        new TelaLogin().setVisible(true);
        
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
       //Limpa-se todos os campos
       tfCpf.setText("");
       tfNome.setText("");
       tfTelefone.setText("");
       tfEndereco.setText("");
       tfNum.setText("");
       tfComplemento.setText("");
       tfCep.setText("");
       tfEmail.setText("");
       pfSenha.setText("");
       tfCpf.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private void lblCepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCepMouseEntered
        //Exibe aviso no lugar correspondente a Label CEP
        //Passar o cursor do mouse em cima da label
        Aviso.setText("Favor preencher somente com números");
    }//GEN-LAST:event_lblCepMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aviso;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNum;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
