/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.framepack;

import br.com.daopack.Connecting;
import java.sql.*;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author DOUGLS
 */
public class TelaLojista extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement ps = null;

    /**
     * Creates new form TelaLojista
     */

    public void cadastrar() {

        String sql = "insert into tbloja(cnpj, nome, telefone, endereco, num, complemento, cep, email, senha) values(?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            //Comando para preparar a conexão com o banco de dados
            ps = conexao.prepareStatement(sql);
            
            /*Os comandos abaixo são para a inserção de dados e quando todos são preenchidos corretamente
            são salvos no banco de dados, podendo assim serem acessados pela tela de login
            */
            ps.setString(1, tfCnpj.getText());
            ps.setString(2, tfNome.getText());
            ps.setInt(3, Integer.parseInt(tfTelefone.getText()));
            ps.setString(4, tfEndereco.getText());
            ps.setString(5, tfNum.getText());
            ps.setString(6, tfComplemento.getText());
            ps.setInt(7, Integer.parseInt(tfCep.getText()));
            ps.setString(8, tfEmail.getText());
            ps.setString(9, pfSenha.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso! Volte para o Menu Login");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Dados inválidos");

        }

    }

    public TelaLojista() {
        initComponents();
        initComponents();
        conexao = Connecting.connect();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        tfCnpj = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();
        tfNum = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        tfCep = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        Aviso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preencha a ficha de Cadastro");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 20, 390, 90);

        lblCnpj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCnpj.setForeground(new java.awt.Color(255, 255, 255));
        lblCnpj.setText("CNPJ:");
        lblCnpj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCnpjMouseEntered(evt);
            }
        });
        getContentPane().add(lblCnpj);
        lblCnpj.setBounds(80, 150, 70, 14);
        getContentPane().add(tfCnpj);
        tfCnpj.setBounds(190, 140, 240, 30);

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(80, 190, 70, 15);
        getContentPane().add(tfNome);
        tfNome.setBounds(190, 180, 240, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 230, 70, 15);
        getContentPane().add(tfTelefone);
        tfTelefone.setBounds(190, 220, 240, 30);

        lblEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço:");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(80, 270, 70, 15);
        getContentPane().add(tfEndereco);
        tfEndereco.setBounds(190, 260, 170, 30);

        lblNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNum.setForeground(new java.awt.Color(255, 255, 255));
        lblNum.setText("Nº");
        getContentPane().add(lblNum);
        lblNum.setBounds(370, 270, 70, 14);
        getContentPane().add(tfNum);
        tfNum.setBounds(390, 260, 40, 30);

        lblComplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(255, 255, 255));
        lblComplemento.setText("Complemento:");
        getContentPane().add(lblComplemento);
        lblComplemento.setBounds(80, 310, 90, 14);
        getContentPane().add(tfComplemento);
        tfComplemento.setBounds(190, 300, 170, 30);

        lblCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCep.setForeground(new java.awt.Color(255, 255, 255));
        lblCep.setText("CEP:");
        lblCep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCepMouseEntered(evt);
            }
        });
        getContentPane().add(lblCep);
        lblCep.setBounds(80, 350, 70, 14);
        getContentPane().add(tfCep);
        tfCep.setBounds(190, 340, 170, 30);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(80, 390, 70, 14);

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(190, 380, 250, 30);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(80, 430, 70, 14);
        getContentPane().add(pfSenha);
        pfSenha.setBounds(190, 420, 250, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 480, 100, 40);

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(300, 480, 100, 40);

        btVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setToolTipText("");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(400, 480, 100, 40);

        Aviso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Aviso.setForeground(new java.awt.Color(255, 255, 255));
        Aviso.setText("Aviso");
        getContentPane().add(Aviso);
        Aviso.setBounds(80, 110, 730, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/viewpack/FundoNovo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 580);

        setSize(new java.awt.Dimension(847, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        //Retorna para o menu anterior
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        //Limpa-se todos os campos
        tfCnpj.setText("");
        tfNome.setText("");
        tfTelefone.setText("");
        tfEndereco.setText("");
        tfNum.setText("");
        tfComplemento.setText("");
        tfCep.setText("");
        tfEmail.setText("");
        pfSenha.setText("");
        tfCnpj.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private void lblCnpjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCnpjMouseEntered
        Aviso.setText("Favor preencher com os caracteres" + "." + "e" + "-" + "");
        //Exibe aviso no lugar correspondente a Label CNPJ
        //Passar o cursor do mouse em cima da label

    }//GEN-LAST:event_lblCnpjMouseEntered

    private void lblCepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCepMouseEntered
        Aviso.setText("Favor preencher somente com números");
        //Exibe aviso no lugar correspondente a Label CNPJ
        //Passar o cursor do mouse em cima da label

    }//GEN-LAST:event_lblCepMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLojista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLojista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLojista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLojista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLojista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aviso;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCnpj;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNum;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
