/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.framepack;





/**
 *
 * @author DOUGLS
 */
public class TelaLogin extends javax.swing.JFrame {

    public TelaLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblCPF = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        rbCliente = new javax.swing.JRadioButton();
        rbLojista = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G8 Store - LOGIN");
        setResizable(false);
        getContentPane().setLayout(null);

        lblCPF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 0));
        lblCPF.setText("Bem vindo a G8 Store!");
        getContentPane().add(lblCPF);
        lblCPF.setBounds(100, 10, 210, 50);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 0));
        lblSenha.setText("Você é:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(60, 70, 50, 15);

        btEntrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar);
        btEntrar.setBounds(160, 170, 80, 30);

        buttonGroup1.add(rbCliente);
        rbCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbCliente.setForeground(new java.awt.Color(255, 255, 0));
        rbCliente.setText("Cliente");
        getContentPane().add(rbCliente);
        rbCliente.setBounds(89, 100, 90, 30);

        buttonGroup1.add(rbLojista);
        rbLojista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbLojista.setForeground(new java.awt.Color(255, 255, 0));
        rbLojista.setText("Lojista");
        getContentPane().add(rbLojista);
        rbLojista.setBounds(230, 100, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/viewpack/26174.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 0, 680, 380);

        setSize(new java.awt.Dimension(434, 290));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        if (rbCliente.isSelected()) {
            new TelaBemVindo().setVisible(true);
            this.dispose();
        } else if (rbLojista.isSelected()) {
            new LoginLojista().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JRadioButton rbLojista;
    // End of variables declaration//GEN-END:variables
}
